// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package geodistancecalculator.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the GeoDistanceCalculator module

	public static java.math.BigDecimal getEARTHRADIUS()
	{
		return (java.math.BigDecimal)Core.getConfiguration().getConstantValue("GeoDistanceCalculator.EARTHRADIUS");
	}

	public static java.lang.String getLOGNODE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GeoDistanceCalculator.LOGNODE");
	}
}