// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package geodistancecalculator.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the GeoDistanceCalculator module
	public static void aCT_CalculateDistanceBetweenGeoPoints(IContext context, geodistancecalculator.proxies.GeolocationHelper _geolocationHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GeolocationHelper", _geolocationHelper == null ? null : _geolocationHelper.getMendixObject());
		Core.microflowCall("GeoDistanceCalculator.ACT_CalculateDistanceBetweenGeoPoints").withParams(params).execute(context);
	}
	public static geodistancecalculator.proxies.GeolocationHelper dSS_GetGeoLocationHelper(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("GeoDistanceCalculator.DSS_GetGeoLocationHelper").withParams(params).execute(context);
		return result == null ? null : geodistancecalculator.proxies.GeolocationHelper.initialize(context, result);
	}
}